### ISSUE TITLE
feat: Design and implement the `Osoc edition overview` page

### ISSUE THREAD

**Issue by KoenDesplenter** [SELab-2/OSOC-2#409]
Implement the entire /osoc frontend route. 

We can split this up in 6 sub tasks:
- [x] Add a form to create a new osoc edition
- [x] Create osoc edition component
- [x] List all osoc editions
- [x] Filter osoc editions
- [x] Make Osoc editions editable
- [x] Remove osoc edition
- [x] Osoc Styling
- [ ] Fix enter not working on text search
- [x] Add new osoc route to api JSON

**Comment by nbeteram** [comment]
@KoenDesplenter is it necessary to have a 'yearSort' parameter in the filterYear route (osoc route) because we only filter on one single year?
