### ISSUE TITLE
Keep localStorage up-to-date

### ISSUE THREAD

**Issue by BramDevlaminck** [SELab-2/OSOC-2#450]
**Describe the bug**
When changing someone's account from admin to no admin,... the 'is_admin' and 'is_coach' don't get updated in localstorage

**To Reproduce**
1. login and go to "manage users" in an admin account
2. login on another account and open the storage tab in the console
3. on the admin account: click on the coach or admin button of the other account you are watching
4. look in local storage of the account you changed. The is_admin and is_coach value doesn't change

**Expected behavior**
is_admin and is_coach should change too in local storage!

## Edit
this might actually not be needed anymore because all the keys get invalidated when needed. This means only the frontend is behind a little until you make your next request. This is not really a problem.

**Comment by Mouwrice** [comment]
The `is_admin` and `is_coach` are no longer stored in localStorage. See #393
