### ISSUE TITLE
Filters not resetting

### ISSUE THREAD

**Issue by HuanYu-Tan** [SELab-2/OSOC-2#498]
**Describe the bug**

**To Reproduce**
1. Go to students
2. Click on the filters
4. See that the filters are not updated

**Expected behavior**
the students should return to the unfiltered states

**Comment by BramDevlaminck** [comment]
This seems te be fixed? We should this confirm this. If this is the case we can close this issue.

**Comment by HuanYu-Tan** [comment]
This issue has been resolved (the problem was most likely related to the deployed db)
