### ISSUE TITLE
conflicts prevention

### ISSUE THREAD

**Issue by BramDevlaminck** [SELab-2/OSOC-2#656]
When assigning a student check if the student application for that year has no assignment.
If it was already assigned => return error with information about where it was already assigned.
This error message will be shown in the frontend

**Comment by jay-tux** [comment]
Closing as this was implemented in [this PR](https://github.com/SELab-2/OSOC-2/pull/567/commits/c4a6e60999fae41d74954280f768e12c6a2fb8f8#diff-a531214a8afde394ba54415852f47a6e8cf9d4e88f94214146f0ea0441f95f38R456) #567 

The current error is 
```ts
{
  http: 409,
  reason: "This student does already have a contract",
}
```
